---
servolist:
- servonummer: 0
  name: "left_eye"
  minvalue: 0
  maxvalue: 4095
  restvalue: 2048
  steps: 10
  factor: 0.3
- servonummer: 1
  name: "right_eye"
  minvalue: 0
  maxvalue: 4095
  restvalue: 2048
  steps: 10
  factor: 0.5

- servonummer: 2
  name: "test"
  minvalue: 0
  maxvalue: 4095
  restvalue: 2048
  steps: 20
  factor: 0.5

- servonummer: 3
  name: "tail"
  minvalue: 200
  maxvalue: 600
  restvalue: 400
  steps: 20
  factor: 0.5

- servonummer: 4
  name: "neck_muscle_right"
  minvalue: 100
  restvalue: 350
  maxvalue: 600  

- servonummer: 5
  name: "neck_muscle_left"
  minvalue: 100
  restvalue: 350
  maxvalue: 600
  factor: 0.5
  steps: 20

- servonummer: 6
  name: "neck_turn"
  minvalue: 100
  restvalue: 350
  maxvalue: 600
  factor: 0.5
  steps: 20


- servonummer: 7
  name: "jaw"
  minvalue: 350
  restvalue: 350
  maxvalue: 500
  factor: 0.5
  steps: 20

- servonummer: 12
  name: "test_servo"
  minvalue: 100
  restvalue: 350
  maxvalue: 600
  factor: 0.5
  steps: 20


- servonummer: 14
  name: "rightwing"
  minvalue: 100
  restvalue: 350
  maxvalue: 600
  factor: 0.5
  steps: 200

- servonummer: 15
  name: "leftwing"
  minvalue: 100
  restvalue: 350
  maxvalue: 600
  factor: 0.5
  steps: 20  
 
debug: false
timestep: 20
actionpath: "D:\\erwin\\dragon\\actions"
randommaxinterval: 200

gamecontroller:
  0: recording
  1: playing
  2: dump
  3: reset
  ry: 4
  rx: tail
  pov: 6
  y: heady
  x: headx
  6: 9
  7: 10
  z: headspin
  4: 12
  5: mouth
